apiVersion: v1
kind: PersistentVolume
metadata:
  name: block-pv
  namespace: default
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath: 
    path: /tmp/data