apiVersion: v1
kind: Pod
metadata:
  name: pod-vpc
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: myvol
        mountPath: "/data"
  volumes:
    - name: myvol
    PersistentVolumeClaim: 
      claimName: storage-pvc
      
