---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cred
  namespace: db
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: YWRtaW4xMjM= 
...

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mariadb-rs
  labels:
    app: mariadb-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-rs
  template:
    metadata:
      labels:
        app: mariadb-rs
    spec:
      containers:
      - name: mariadb
        image: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-cred
                key: MARIADB_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-volume
      volumes:
      - name: mariadb-volume
        awsElasticBlockStore:
          volumeID: vol-0a0ae4c0c1009276c 
          fsType: ext4
...
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-rs-svc
spec:
  selector:
    app: mariadb-rs
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
...
