apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-05
  labels:
    app: nginx-01
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
         ports:
        - containerPort: 80
