apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-deployment-03
  labels:
    app: centos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: centos
        
