apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rolling-update
  labels:
    app: nginx
spec:
  strategy:
     type: RollingUpdate
     rollingUpdate:
         maxSurge: 1
         maxUnavailable: 1
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
