---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cource-config
data:
  NAME: Kaustubh
  TIMING: 10AM
...

---
apiVersion: v1
kind: Pod
metadata: 
  name: congif-maps-var
spec: 
  containers: 
    - name: httpd
      image: sachet1994/httpd:v1
      env: 
        - name: NAME
          valueFrom:
            configMapKeyRef: 
              name: cource-config
              key: NAME 
        - name: TIMING
          valueFrom:
            configMapKeyRef: 
              name: cource-config
              key: TIMING 
...
