apiVersion: v1
kind: Pod
metadata: 
  name: multi-container
spec: 
  containers: 
    - name: httpd
      image: sachet1994/httpd:v1

    - name: centos
      image: centos
      command: ["sleep", "10000"]
      