---
apiVersion: v1
kind: Secret
metadata:
  name: myscrete
type: Opaque 
data:
  MARIADB_ROOT_PASSWORD: YWRtaW4xMjM=
... 

---
apiVersion: v1
kind: Pod
metadata: 
  name: mariadb
spec: 
  containers: 
    - name: mariadb 
      image: mariadb
      env: 
        - name: MARIADB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: myscrete
              key:  MARIADB_ROOT_PASSWORD 
...
