apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrete
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: DB-CREDENTIALS